# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is NOT reloaded automatically.
# If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sam Wilson
email: samwilsonme@gmail.com
description: Sam Wilson - General Manager at Art of Flooring - Based in Cambridge, UK
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.samwilson.me # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-54644459-1
google_tagmanager: GTM-NPW6V96

# social: [name, icon, website, username]
#instagram: ['Instagram', 'instagram', 'https://instagram.com/', 'samwilsonme']
#linkedin: ['LinkedIn', 'linkedin', 'https://www.linkedin.com/in/', 'samwilsonme']
#github: ['GitHub', 'github-alt', 'https://github.com/', 'samwilsonme']

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
- package.json
- bower.json
- gulpfile.js
- gulpconfig.yml
- Gemfile
- Gemfile.lock
- README.md
- node_modules
- bower_components
- assets/scss
